### ISSUE TITLE
enable non-English characters (UTF-8)

### ISSUE THREAD

**Issue by noamoss** [nopeslide/drawio_mermaid_plugin#1]
When typing in non-English characters (in this example, Hebrew letters), the graph is not rendered correctly (`string contains invalid characters` message is shown).

![image](https://user-images.githubusercontent.com/3581741/74033876-bc99d200-49bf-11ea-9ca7-0ce8ed43548d.png)

Mermaid.js can handle Hebrew characters, as can be seen [here](https://mermaid-js.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5bKl0gLS0-INei15PXmdeZ159cbtei15PXmdeZ158gLS0-IFsqXVxuXG7XoteT15nXmdefIC0tPiDXlteW15nXnVxu15bXlteZ150gLS0-INei15PXmdeZ159cbteW15bXmdedIC0tPiDXlNeq16DXktep15XXqlxu15TXqteg15LXqdeV16ogLS0-IFsqXSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19) with the same input:

```
stateDiagram
[*] --> עדיין
עדיין --> [*]

עדיין --> זזים
זזים --> עדיין
זזים --> התנגשות
התנגשות --> [*]
```

**Comment by nopeslide** [comment]
@noamoss plz leave a comment if this is fixed now.

**Comment by noamoss** [comment]
@nopeslide perfect!

![image](https://user-images.githubusercontent.com/3581741/74089966-1dec9e80-4aaf-11ea-96bd-e9777a7c5878.png)


Thanks a lot.
