### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by Cyrille37** [nopeslide/drawio_mermaid_plugin#127]
Hi
Thanks a lot for this great plugin.

With
- diagrams.net 16.5.1 (desktop .deb linux package)
- drawio_mermaid_plugin 0.1.5

Drag a Mermaid sequence diagram on a page throw error "Uncaught URIError: URI malformed" but the diagram is well drawn.
Click "Apply" after editing the Mermaid diagram without syntax error throw the same error but without drawing changes.

Regards & cheers

**Comment by nopeslide** [comment]
thanks for reporting this.
I will take a look in a few weeks, sadly I got no time atm

**Comment by novski** [comment]
same on macos desktop 17.4.2 today

**Comment by fast01** [comment]
i got the same error too !   draw.io  macos  desktop version  17.4.2  @nopeslide   so, this is  a certain issue~ 

hope a  fix version for this. 

Regards~

**Comment by AhmedThahir** [comment]
Any updates?

**Comment by rpeyron** [comment]
Hello, 

The cause of the problem is newer versions of drawio expecting default values of custom properties to be URI encoded, but axisFormat default value is not (%Y-%m-%d) and cause the issue.

Adding encodeURIComponent to default value solve the issue:
```
        { name: 'gantt_axisFormat', dispName: 'gantt_axisFormat', type: 'string', defVal: encodeURIComponent(defaults.gantt.axisFormat) },

```

(Fix included also in PR #144)

**Comment by andyinthedream** [comment]
> 

Hello,
I found same problem in my macos drawio desktop20.3.0, I found your reply that mentioned the solution about this problem, but I dont known how to add encodeURIComponent to default value.

I'm appreciate that if you can provide more detailed solution, thanks!!

**Comment by rpeyron** [comment]
Hi @andyinthedream  the line to modify is in the source code. To facilitate things waiting for nopeslide to get the time to publish a new release, I compiled one including the fix here : https://github.com/nopeslide/drawio_mermaid_plugin/releases/tag/v0.1.5
Hope this helps

**Comment by jfroco** [comment]
It worked when I installed the plugin from:  https://github.com/rpeyron/drawio_mermaid_plugin/releases/tag/0.1.5%2B20230606
(I'm using v20.7.4).
Hope this helps.

**Comment by Cyrille37** [comment]
Thanks to wake up me ;-)

It works for me too

- diagrams.net 20.7.4
- drawio_mermaid_plugin 0.1.5

**Comment by akutz** [comment]
FWIW, this is occurring again with the latest draw.io desktop release https://github.com/jgraph/drawio-desktop/releases/tag/v26.2.2.

**Comment by rpeyron** [comment]
Hello, I have just checked the v26.2.2 and it seems to be working OK with https://github.com/rpeyron/drawio_mermaid_plugin/releases/tag/0.1.5%2B20230606
