### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by hediet** [nopeslide/drawio_mermaid_plugin#13]
Nice to see that v0.1.1 is available! I really like the dialog with the error reporting!

It would be nice to have a changelog though! You can find some recommendations here: https://keepachangelog.com/.

You can link the changelog from package.json of the VS Code extension so that it appears in the marketplace.

A changelog helps users to keep track of the updates. Otherwise they have to go through your commits to see what changed ;)

**Comment by nopeslide** [comment]
fixed with v0.1.2
