### ISSUE TITLE
Document How To Install As VS Code Extension

### ISSUE THREAD

**Issue by hediet** [nopeslide/drawio_mermaid_plugin#3]
Nice job on the vscode extension and this awesome drawio plugin!

It would be handy if you could link to your extension in the marketplace and also include screenshots!

**Comment by nopeslide** [comment]
have to rewrite the install documentation anyway,
because draw.io altered the dialogs.

**Comment by hediet** [comment]
You should probably have a different readme for the vscode extension and for your repository!

**Comment by nopeslide** [comment]
vscode expects the readme to be in the root directory and ignores the package.json,
so I would have to move stuff around while building.
Want to keep it simple, stupid, therefore would go with a global one.

**Comment by hediet** [comment]
> vscode expects the readme to be in the root directory and ignores the package.json,

You can change that!

**Comment by nopeslide** [comment]
the readme options is ignored. tested it

**Comment by hediet** [comment]
I suggest to move everything related to VS Code in its own folder.
You can use a webpack loader to bundle your mermaid plugin, then you don't need to load it from the file.

**Comment by nopeslide** [comment]
>  You can use a webpack loader to bundle your mermaid plugin, then you don't need to load it from the file.

you mean by utilizing `file-loader`? letting it put the plugin bundle into the output dir and use the returned file uri instead of the `__dirname` constructed path?

**Comment by hediet** [comment]
> you mean by utilizing file-loader? letting it put the plugin bundle into the output dir and use the returned file uri instead of the __dirname constructed path?

Yes!

**Comment by hediet** [comment]
If you like, I can advertise your extension on Twitter as soon as it hits version 0.1.0!

**Comment by nopeslide** [comment]
> If you like, I can advertise your extension on Twitter as soon as it hits version 0.1.0!

Got no problem with it.
Do you spot anything else in the current build?

**Comment by hediet** [comment]
Except the readme, no ;)

**Comment by nopeslide** [comment]
jfyi I updated the readme :o

**Comment by hediet** [comment]
Awesome, much better! You should add a link to your extension in the marketplace though so that people can directly install it!
